const titles={dashboard:'Skills Dashboard',learn:'Learning Modules',scripts:'Sample Script Library',practice:'AI Practice Simulator',markets:'Industry Explorer',progress:'Progress & Mastery'};
function show(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));document.querySelector('#title').textContent=titles[id]}
window.show=show;
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>show(b.dataset.view));
const modules=[
['Introduction to Non-Voice Contact Center Services','Voice vs. non-voice; live chat, email, messaging, ticketing, social media support, back-office services, and common non-voice products and services.','Classify examples according to channel and service type.'],
['Written Communication Skills for Customer Service','Grammar, spelling, punctuation, sentence construction, clarity, conciseness, professional vocabulary, and avoiding inappropriate slang or text language.','Edit poorly written customer-service messages.'],
['Professional Tone, Netiquette, and Customer Empathy','Professional online behavior, positive language, courtesy, empathy, cultural sensitivity, and adapting written tone for different customers.','Rewrite negative messages using professional and empathetic language.'],
['Understanding Customer Concerns and Non-Voice Probing','Reading comprehension, identifying customer intent, analyzing the concern, open- and closed-ended questions, clarification, verification, and probing techniques.','Analyze customer messages and prepare appropriate probing questions.'],
['The Non-Voice Chat Flow and Actual Script Analysis','Opening → Verification → Acknowledgment → Probing → Resolution → Confirmation → Additional Assistance → Closing.','Label every part of the sample script.',`Agent: Good morning! Thank you for contacting ABC Online Support. My name is Ana. How may I assist you today?\nCustomer: My order has not arrived.\nAgent: I’m sorry about the delay. I understand how important it is to receive your order on time. May I have your order number for verification?\nCustomer: It is 48291.\nAgent: Thank you. When did the tracking status last change?\nCustomer: Three days ago.\nAgent: I checked the order and it is at the local delivery hub. I will contact the courier and update you within two hours. Would that be acceptable?\nCustomer: Yes, thank you.\nAgent: You’re welcome. Is there anything else I can assist you with today?\nCustomer: None.\nAgent: Thank you for contacting ABC Online Support. Have a great day!`],
['Chat and Email Response Writing','Professional chat responses and emails; greetings, acknowledgment, empathy, hold statements, resolutions, email structure, and professional closings.','Answer one chat concern and compose one support email.'],
['Handling Difficult Customers and Common Scenarios','Angry, impatient, confused, and dissatisfied customers; complaints, billing, refunds, orders, accounts, and basic technical concerns.','Respond to three difficult-customer scenarios.'],
['Problem Solving, Knowledge Base, Escalation, and Documentation','Knowledge base and FAQ searches, solutions, policies, escalation, transfers, ticket creation, disposition, and case notes.','Resolve a case and prepare its ticket notes.'],
['Non-Voice Quality Standards and Guided Practice','Accuracy, grammar, tone, empathy, response time, completeness, data privacy, documentation, QA scoring, and guided scenario practice.','Score and improve a sample conversation.'],
['Mock and Final Non-Voice Simulation','Students independently perform realistic chat and email transactions using the complete process; the teacher evaluates performance using a rubric.','Complete the timed mock, review feedback, and take the final simulation.']
];
document.querySelector('#modules').innerHTML=modules.map((m,i)=>`<article class="lessoncard" data-lesson="${i}"><label>LESSON ${i+1}</label><h3>${m[0]}</h3><p>${m[1]}</p><button>Open Lesson in New Tab ↗</button></article>`).join('');
document.querySelectorAll('.lessoncard').forEach(c=>c.onclick=()=>window.open(`index.html?lesson=${c.dataset.lesson}`,'_blank'));
const lessonBodies=[
 {objectives:['Define non-voice contact center services','Differentiate voice and non-voice transactions','Identify products, services, and employment markets'],sections:[['What is non-voice support?','Non-voice support assists customers through written digital channels. Agents must understand the concern, find accurate information, and provide a clear written resolution without relying on spoken explanations.'],['Major channels','Live chat provides real-time written assistance. Email handles detailed or non-urgent concerns. Messaging and social media support customers on mobile platforms. Ticketing records and tracks cases. Back-office work includes data entry, verification, order processing, and content review.'],['Potential markets','E-commerce, banking, telecommunications, healthcare, travel, technology, logistics, insurance, education, and government all use non-voice services.']],example:'A customer asking where an online order is should be handled through live chat or messaging. A request requiring documents and a detailed explanation is often better handled through email or ticketing.',check:['What makes a transaction non-voice?','Name four non-voice channels.','Give two industries that hire non-voice agents.']},
 {objectives:['Apply correct grammar and punctuation','Write concise customer-friendly sentences','Use professional vocabulary'],sections:[['Accuracy matters','Incorrect grammar or spelling can change meaning and reduce customer confidence. Agents must proofread names, dates, amounts, instructions, and policy information.'],['Clarity and conciseness','Use short complete sentences, one idea at a time, and familiar words. Remove repetition, unnecessary fillers, excessive capitalization, and multiple punctuation marks.'],['Professional language','Avoid shortcuts such as “u,” “pls,” “ASAP!!!,” and informal slang. Use “you,” “please,” “I will check this for you,” and other complete expressions.']],example:'Weak: “pls wait im checking ur acc.”\nImproved: “Please allow me a moment while I review your account.”',check:['Correct this: “your order have been ship.”','Why should agents avoid text-message shortcuts?','What information must always be proofread?']},
 {objectives:['Use appropriate netiquette','Demonstrate empathy in writing','Adapt tone to customer emotions and culture'],sections:[['Professional netiquette','Greet the customer, respond respectfully, avoid typing in all caps, do not argue, and never make jokes that may be misunderstood. Maintain privacy and stay focused on the concern.'],['Empathy and acknowledgment','Acknowledgment shows that the concern was understood. Empathy recognizes its effect on the customer. Use genuine statements connected to the specific situation.'],['Positive language','Focus on what can be done. Replace “That is impossible” with “Here are the available options.” Avoid blaming the customer, another department, or the company.']],example:'“I understand how frustrating it is to be charged twice. I’ll review both transactions and help you resolve this.”',check:['What is the difference between acknowledgment and empathy?','Rewrite: “You entered the wrong information.”','Why can humor be risky in live chat?']},
 {objectives:['Identify the customer’s main intent','Distinguish open and closed questions','Use clarification, verification, and probing'],sections:[['Read before responding','Review the whole message and separate the main concern from supporting details. Do not ask for information the customer already provided.'],['Types of questions','Open questions gather explanations: “What happened before the error appeared?” Closed questions confirm facts: “Did you receive a confirmation email?” Clarifying questions remove ambiguity, while verification confirms identity or transaction details.'],['Effective probing','Ask one relevant question at a time. Explain why sensitive information is needed, follow data-privacy rules, and summarize the facts before giving a solution.']],example:'Customer: “It does not work.”\nUseful probes: “Which feature are you trying to use?” “What message appears on the screen?” “When did the problem begin?”',check:['What is the customer’s intent? “I paid yesterday but my balance is unchanged.”','Write one open and one closed question.','Why should agents avoid repeated questions?']},
 {objectives:['Follow the eight-stage chat flow','Analyze an actual chat script','Use transitions naturally'],sections:[['Opening and verification','Welcome the customer, introduce yourself, offer assistance, and verify only the information required by policy.'],['Acknowledgment, probing, and resolution','Recognize the concern and its impact, ask focused questions, consult the correct resource, then give an accurate resolution and timeframe.'],['Confirmation and closing','Confirm that the solution is understood, offer additional assistance, thank the customer, and close professionally.']],example:'Use the sample script below. Notice how the agent does not give a solution before verification and probing.',check:['Which stage comes after acknowledgment?','Why must the agent confirm the resolution?','Identify the closing statement in the sample script.']},
 {objectives:['Construct professional chat messages','Write a properly structured support email','Use hold and closing statements'],sections:[['Chat response structure','A strong response usually contains acknowledgment, empathy when appropriate, action, and expectation. Keep messages readable and send updates during long checks.'],['Hold procedure','Ask permission before a hold, give a reasonable duration, return within the promised time, thank the customer for waiting, and provide an update.'],['Email structure','Use a clear subject, greeting, acknowledgment, organized explanation, action or next step, additional-assistance line, and professional signature.']],example:'Subject: Update on Order 48291\nDear Ms. Santos,\nI’m sorry for the delivery delay. I contacted the courier and requested priority delivery. You will receive another update within two hours.\nSincerely,\nAna | Customer Support',check:['What four parts should a strong chat response contain?','Write a proper hold statement.','What makes an email subject effective?']},
 {objectives:['De-escalate difficult conversations','Respond to common support scenarios','Offer realistic policy-compliant options'],sections:[['Control the interaction','Stay calm, acknowledge the concern, avoid defensive language, and focus on facts and solutions. Never tell a customer to “calm down.”'],['Common difficult behaviors','An angry customer needs acknowledgment and action. An impatient customer needs a clear timeframe. A confused customer needs simple steps. A dissatisfied customer needs confirmation that the proposed option addresses the concern.'],['Boundaries and promises','Do not invent policies, guarantee outcomes outside your control, or provide unauthorized refunds. Explain available options and escalate when necessary.']],example:'Instead of “That is not our fault,” write: “I understand why this is concerning. Let me review the transaction and identify the available solution.”',check:['Why should an agent avoid telling a customer to calm down?','How do you respond to an impatient customer?','When should a complaint be escalated?']},
 {objectives:['Use a knowledge base effectively','Apply escalation rules','Create complete case documentation'],sections:[['Knowledge-base search','Use specific keywords, confirm that the article matches the product and current policy, follow the steps in order, and translate technical instructions into customer-friendly language.'],['Escalation','Escalate when access or authority is insufficient, a policy exception is requested, a security or safety issue exists, or troubleshooting has failed. Explain the transfer and pass complete context.'],['Documentation','Record the customer’s concern, verified information, troubleshooting performed, solution offered, commitments, follow-up time, and disposition. Use objective language.']],example:'Case note: “Customer reported duplicate charge of ₱850 dated 1 September. Verified both transaction IDs. Explained pending-charge policy and escalated to Billing Review. Advised update within 24 hours.”',check:['What should be checked before using a knowledge article?','List two reasons for escalation.','What information belongs in a case note?']},
 {objectives:['Apply non-voice QA standards','Protect customer data','Evaluate and improve a transcript'],sections:[['Core QA standards','Quality reviews measure accuracy, grammar, tone, empathy, completeness, process compliance, response time, resolution, and documentation. Critical errors may outweigh other good performance.'],['Data privacy','Collect only necessary information, use approved verification, never request passwords or one-time PINs, avoid copying personal data into unauthorized tools, and follow retention rules.'],['Guided practice','Review the scenario, draft a response, compare it with the rubric, revise weak areas, and repeat until the required score is reached.']],example:'A grammatically perfect response still fails QA if it gives the wrong refund policy or exposes personal information.',check:['Name five non-voice QA criteria.','What information must an agent never request?','Why is accuracy more important than speed?']},
 {objectives:['Complete an end-to-end chat or email case','Work independently within time limits','Meet the teacher’s performance rubric'],sections:[['Mock simulation','The mock reproduces the assessment conditions. Students receive a customer scenario, use the full chat flow, document the case, and review detailed teacher feedback.'],['Final simulation','Students independently handle one chat and one email concern. The teacher evaluates written communication, empathy, probing, resolution, process compliance, documentation, and efficiency.'],['Suggested scoring','Written communication 20%; tone and empathy 15%; probing and verification 15%; accurate resolution 20%; chat flow 15%; documentation and privacy 10%; efficiency 5%.']],example:'Passing recommendation: at least 75% overall with no critical error involving privacy, verification, misinformation, or unprofessional conduct.',check:['What are the two required final transactions?','Which performance area has the highest suggested weight?','What is considered a critical error?']}
];
const knowledgeAnswers=[
 ['It uses written digital channels instead of a phone conversation.','Live chat, email, messaging, ticketing, social media, and back-office processing are examples.','Examples include e-commerce, banking, telecommunications, healthcare, travel, and technology.'],
 ['Correct: “Your order has been shipped.”','Shortcuts can appear careless, confuse customers, and damage professional credibility.','Names, dates, amounts, order numbers, instructions, and policy details must be proofread.'],
 ['Acknowledgment confirms the concern; empathy recognizes how the situation affects the customer.','Improved: “Let me help you correct the information so we can continue.”','Written humor can be misunderstood because tone and facial expressions are absent.'],
 ['The customer wants confirmation that yesterday’s payment will be posted to the account.','Open: “What happened after you submitted the payment?” Closed: “Did you receive a receipt?”','Repeated questions frustrate customers and show that the agent did not read carefully.'],
 ['Probing comes after acknowledgment.','Confirmation ensures the customer understands and accepts the proposed resolution.','The final thank-you and well-wish form the closing statement.'],
 ['Acknowledgment, empathy, action, and expectation.','“May I place the chat on hold for two minutes while I review your account?”','A useful subject states the purpose clearly, such as “Update on Order 48291.”'],
 ['It sounds dismissive and can make the customer more upset.','Acknowledge the urgency and give an honest, specific timeframe.','Escalate when authority is insufficient, a policy exception is needed, or risk/security is involved.'],
 ['Confirm that it matches the correct product, issue, customer type, and current policy.','Examples: insufficient authority, failed troubleshooting, security risk, or requested policy exception.','Concern, verification, steps taken, resolution, commitments, follow-up time, and disposition.'],
 ['Accuracy, grammar, tone, empathy, completeness, response time, privacy, resolution, and documentation.','Never request a password or one-time PIN.','A fast but incorrect answer can harm the customer and create a critical quality failure.'],
 ['One live-chat transaction and one email transaction.','Written communication and accurate resolution receive the highest suggested weights at 20% each.','Examples include privacy violations, failed verification, misinformation, and unprofessional conduct.']
];
function openLesson(i){const m=modules[i],b=lessonBodies[i],done=localStorage.getItem(`bnhs-lesson-${i}`)==='done';document.querySelectorAll('.lessoncard').forEach((c,n)=>c.classList.toggle('selected',n===i));document.querySelector('#lessonDetail').innerHTML=`<div class="lessonTop"><div><small>INTERACTIVE LESSON ${i+1} OF 10</small><h1>${m[0]}</h1></div><span class="status ${done?'complete':''}" id="lessonStatus">${done?'✓ Completed':'In progress'}</span></div><div class="lessonProgress"><i style="width:${(i+1)*10}%"></i></div><section class="lessonBlock"><h2>Why This Lesson Matters</h2><p>${m[1]}</p><p>As a non-voice agent, you must apply this knowledge while reading, thinking, and responding under time pressure. Study the explanations and connect each idea to the examples before attempting the activity.</p></section><section class="lessonBlock"><h2>Learning Objectives</h2><ul>${b.objectives.map(x=>`<li>${x}</li>`).join('')}</ul></section>${b.sections.map((x,n)=>`<details class="topic" ${n===0?'open':''}><summary>${n+1}. ${x[0]}</summary><div><p>${x[1]}</p><p><b>Think about it:</b> How would this concept affect the customer’s experience if an agent ignored it?</p></div></details>`).join('')}${i===4?`<section class="lessonBlock"><h2>Complete Chat Flow</h2><div class="flow">Opening → Verification → Acknowledgment → Probing → Resolution → Confirmation → Additional Assistance → Closing</div><p>Each stage has a purpose. Skipping verification can create a privacy risk, while skipping confirmation may leave the customer unsure whether the concern was resolved.</p></section>`:''}<section class="lessonBlock"><h2>Worked Example</h2><div class="sample">${b.example}</div></section>${m[3]?`<section class="lessonBlock"><h2>Actual Sample Script</h2><div class="sample">${m[3]}</div></section>`:''}<section class="lessonBlock"><h2>Try It Yourself</h2><div class="activity">${m[2]}</div><textarea class="studentWork" id="studentWork" placeholder="Write your answer, analysis, or draft response here..."></textarea><button class="saveWork" onclick="saveWork(${i})">Save My Work</button><span id="saveNote"></span></section><section class="lessonBlock"><h2>Interactive Knowledge Check</h2><p>Answer each question first, then reveal the suggested answer.</p>${b.check.map((x,q)=>`<div class="question"><b>${q+1}. ${x}</b><textarea placeholder="Type your answer..."></textarea><button onclick="revealAnswer(${i},${q},this)">Show Suggested Answer</button><div class="answer"></div></div>`).join('')}</section><div class="lessonNav"><button ${i===0?'disabled':''} onclick="goLesson(${i-1})">← Previous Lesson</button><button class="completeBtn" onclick="completeLesson(${i})">✓ Mark Lesson Complete</button><button ${i===9?'disabled':''} onclick="goLesson(${i+1})">Next Lesson →</button></div>`;document.querySelector('#studentWork').value=localStorage.getItem(`bnhs-work-${i}`)||'';document.querySelector('#lessonDetail').scrollIntoView({block:'start'})}
window.revealAnswer=(i,q,btn)=>{const box=btn.nextElementSibling;box.textContent=knowledgeAnswers[i][q];box.classList.toggle('show');btn.textContent=box.classList.contains('show')?'Hide Suggested Answer':'Show Suggested Answer'};
window.saveWork=i=>{localStorage.setItem(`bnhs-work-${i}`,document.querySelector('#studentWork').value);document.querySelector('#saveNote').textContent=' ✓ Saved on this device'};
window.completeLesson=i=>{localStorage.setItem(`bnhs-lesson-${i}`,'done');document.querySelector('#lessonStatus').className='status complete';document.querySelector('#lessonStatus').textContent='✓ Completed'};
window.goLesson=i=>{location.href=`index.html?lesson=${i}`};
const selectedLesson=new URLSearchParams(location.search).get('lesson');if(selectedLesson!==null&&!Number.isNaN(+selectedLesson)&&+selectedLesson>=0&&+selectedLesson<10){show('learn');document.body.classList.add('lessonMode');document.querySelector('#modules').style.display='none';openLesson(+selectedLesson)}
const markets=[['E-commerce & Retail','Order support, returns, refunds, product inquiries'],['Banking & Finance','Account support, verification, fraud reporting'],['Telecommunications','Billing, plan changes, connectivity support'],['Healthcare','Appointment, benefits, and patient-service support'],['Travel & Hospitality','Reservations, rebooking, guest assistance'],['Technology & SaaS','Help desk, onboarding, subscription support'],['Logistics','Tracking, delivery coordination, claims'],['Insurance','Policy inquiries, claims intake, documentation'],['Education & Government','Enrollment, public information, service requests']];
document.querySelector('#marketgrid').innerHTML=markets.map((x,i)=>`<article class="marketCard" data-market="${i}"><h3>${x[0]}</h3><p>${x[1]}</p><b>Start AI Practice →</b></article>`).join('');
document.querySelectorAll('.marketCard').forEach(c=>c.onclick=()=>startMarketPractice(+c.dataset.market));
const marketScenarios=[
 {title:'Delayed Online Order',name:'Mia Santos',situation:'The package was promised yesterday, but tracking has not changed for three days.',opening:'This is already late and I need it for a birthday tomorrow. What is happening?',replies:['My order number is BNHS-48291. Can you check it?','Tracking only says “in transit.” Can it arrive tomorrow?','What other option can you offer if it cannot arrive?','A pickup replacement would help. Is there an extra charge?','Please arrange it and confirm where I should go.','Thank you for helping me.']},
 {title:'Unrecognized Bank Transaction',name:'Carlo Reyes',situation:'The customer sees an unfamiliar ₱2,450 debit and is worried about account security.',opening:'There is a ₱2,450 charge I do not recognize. Is my account compromised?',replies:['The transaction date is today. What should I do first?','Can you block further transactions without closing my account?','Will I get the money back?','How long will the investigation take?','Please confirm the case number and next step.','Thank you. I feel safer now.']},
 {title:'Mobile Data Not Working',name:'Jessa Cruz',situation:'The customer renewed a mobile plan, but cellular data still does not work.',opening:'I renewed my plan this morning, but I still have no mobile data.',replies:['My payment confirmation number is TEL-73105.','I already restarted the phone twice.','The signal bars are visible, but websites will not load.','Will resetting the network delete my files?','I completed the steps and it is working now.','Thanks for explaining everything clearly.']},
 {title:'Urgent Appointment Request',name:'Daniel Lim',situation:'The customer needs to reschedule a clinic appointment because symptoms have worsened.',opening:'My appointment is next week, but I am feeling worse. Can I get an earlier schedule?',replies:['My patient reference is HC-19028.','The earliest online slot is still next week.','Can you check cancellations or another doctor?','Tomorrow afternoon would be possible for me.','Please confirm the clinic location and time.','Thank you for arranging it.']},
 {title:'Flight Rebooking Concern',name:'Angela Flores',situation:'A flight was cancelled and the customer needs to attend an important event.',opening:'My flight was cancelled, and I need to arrive before Friday evening.',replies:['My booking code is TR-88214.','Are there flights through another city?','Will I have to pay a fare difference?','The Friday morning option will work.','Please send the updated itinerary by email.','Thank you for finding an alternative.']},
 {title:'Locked Software Account',name:'Paolo Garcia',situation:'The customer cannot access a work account after several unsuccessful login attempts.',opening:'My account is locked and I have a report due in one hour. Please help.',replies:['My registered email is p.garcia@example.com.','I did not receive the reset email.','I checked spam and it is not there.','Can you resend it or verify another way?','The new link worked and I am logged in.','Thank you for the quick support.']},
 {title:'Missing Delivery Package',name:'Rose Mendoza',situation:'Tracking says delivered, but the package cannot be found.',opening:'The tracking says delivered, but there is no package at my address.',replies:['The tracking number is LG-55192.','I checked with my family and neighbors.','The delivery photo does not show my house.','Can the driver return or can you open a claim?','Please send me the claim reference number.','Thank you. I will wait for the update.']},
 {title:'Insurance Claim Status',name:'Mark Villanueva',situation:'The customer submitted documents for a vehicle claim but has received no update.',opening:'I submitted all my claim documents ten days ago. Why is there no update?',replies:['My claim number is IN-40327.','I uploaded the police report and repair estimate.','Which document is still missing?','Can I upload the signed form through this chat?','Please confirm the review timeframe after submission.','Thank you for checking my claim.']},
 {title:'Student Enrollment Record',name:'Lea Ramos',situation:'An enrolled student cannot see one subject in the online portal.',opening:'I enrolled last week, but one required subject is missing from my portal.',replies:['My learner reference is ED-60218.','The missing subject is Contact Center Services.','It appears on my registration form but not online.','Will this affect my attendance record?','Please confirm when the portal will update.','Thank you for helping me fix the record.']}
];
const serviceScripts=[
 ['E-commerce & Retail',['Opening|Good day! Thank you for contacting ShopEase Support. My name is Ana. How may I help you?','Acknowledgment|I’m sorry your order has not arrived as promised. I understand that you need it for tomorrow.','Verification|May I have your order number and the name registered on the order?','Probing|Thank you. When did the tracking status last change?','Resolution|The package is at the local hub. I will request priority delivery and update you within two hours.','Confirmation|Would priority delivery still meet your need?','Additional Assistance|Is there anything else I can assist you with today?','Closing|Thank you for contacting ShopEase Support. Have a great day!']],
 ['Banking & Finance',['Opening|Welcome to SecureBank Chat Support. I’m Carlo. How may I assist you?','Acknowledgment|I understand how concerning an unfamiliar transaction can be. I’ll help you secure the account.','Verification|For security, please verify your full name and the last four digits of the account. Never send your PIN or password.','Probing|What is the amount and transaction date shown in your account?','Resolution|I have placed a temporary card restriction and created a dispute case for ₱2,450. Review takes up to five business days.','Confirmation|Would you like a replacement card delivered to your registered address?','Additional Assistance|Do you need help reviewing any other recent transactions?','Closing|Your dispute reference is SB-24851. Thank you for contacting SecureBank.']],
 ['Telecommunications',['Opening|Thank you for chatting with ConnectTel. My name is Jessa. How may I help?','Acknowledgment|I’m sorry your mobile data is unavailable after renewal. Let’s restore the connection.','Verification|May I have your mobile number and payment confirmation reference?','Probing|Do you see signal bars, and have you already restarted the phone?','Resolution|Please turn airplane mode on for 30 seconds, turn it off, then reset the network settings. This will not delete personal files.','Confirmation|Please try opening a webpage. Is the data connection working now?','Additional Assistance|Would you like instructions for checking your remaining data balance?','Closing|Thank you for choosing ConnectTel. Have a connected day!']],
 ['Healthcare',['Opening|Good morning. You have reached CarePoint Appointment Support. I’m Daniel. How may I assist you?','Acknowledgment|I’m sorry you are feeling worse. I’ll check the earliest available appointment.','Verification|May I have your patient reference and date of birth for verification?','Probing|Are you requesting a particular doctor, and what schedules can you attend?','Resolution|A cancellation opened tomorrow at 2:30 p.m. with Dr. Santos at the Main Clinic.','Confirmation|Would you like me to reserve that appointment?','Additional Assistance|Do you need the clinic address or preparation instructions?','Closing|Your appointment is confirmed under HC-19028. If symptoms become severe, seek urgent medical care.']],
 ['Travel & Hospitality',['Opening|Welcome to SkyJourney Support. My name is Angela. How may I assist you?','Acknowledgment|I’m sorry your flight was cancelled, especially with an important event approaching.','Verification|May I have your booking code and passenger name?','Probing|What is the latest acceptable arrival time, and are connecting flights acceptable?','Resolution|I found a Friday morning flight through Cebu with no additional fare.','Confirmation|Would you like me to rebook you on this itinerary?','Additional Assistance|Do you need assistance with baggage or seat selection?','Closing|The updated itinerary has been emailed. Thank you for choosing SkyJourney.']],
 ['Technology & SaaS',['Opening|Hello! Thank you for contacting WorkCloud Technical Support. I’m Paolo. How can I help?','Acknowledgment|I understand the urgency of accessing your report. Let’s restore your account safely.','Verification|Please confirm your registered email. Do not send your password.','Probing|Did you receive a reset email, and have you checked the spam folder?','Resolution|I have generated a new secure reset link valid for 15 minutes.','Confirmation|Please use the link now and confirm whether you can access the account.','Additional Assistance|Would you like help enabling two-factor authentication?','Closing|Your access is restored. Thank you for using WorkCloud.']],
 ['Logistics',['Opening|Thank you for contacting FastTrack Logistics. I’m Rose. How may I assist you?','Acknowledgment|I’m sorry the package is marked delivered but cannot be located. I’ll investigate it.','Verification|May I have the tracking number and complete delivery address?','Probing|Have you checked with household members, neighbors, and the delivery photo?','Resolution|The photo does not match your address, so I opened a driver investigation and missing-package claim.','Confirmation|Is email your preferred way to receive the investigation update?','Additional Assistance|Do you need the merchant informed of the claim?','Closing|Your claim reference is LG-55192. We will update you within 24 hours.']],
 ['Insurance',['Opening|Welcome to ShieldSure Claims Support. My name is Mark. How may I help you?','Acknowledgment|I’m sorry you have waited ten days without a claim update. I’ll review the documents.','Verification|May I have the claim number and policyholder name?','Probing|Did you upload the police report, repair estimate, and signed claim form?','Resolution|The signed claim form is missing. I will send a secure upload link now; review resumes once received.','Confirmation|Did you receive the link, and can you upload the form today?','Additional Assistance|Would you like a checklist of the remaining claim steps?','Closing|We will update you within two business days after upload. Thank you for contacting ShieldSure.']],
 ['Education & Government',['Opening|Good day! You have reached the Student Services Help Desk. I’m Lea. How may I assist you?','Acknowledgment|I understand your concern about the missing subject and its effect on attendance.','Verification|May I have your learner reference number and registered full name?','Probing|Which subject is missing, and does it appear on your registration form?','Resolution|The subject is approved but awaiting portal synchronization. I submitted a correction request for processing today.','Confirmation|Would you like the request confirmation sent to your school email?','Additional Assistance|Do you need help checking your other enrolled subjects?','Closing|Your request reference is ED-60218. Thank you for contacting Student Services.']]
];
document.querySelector('#scriptMenu').innerHTML=serviceScripts.map((s,i)=>`<button data-script="${i}">${s[0]}</button>`).join('');
document.querySelectorAll('#scriptMenu button').forEach(b=>b.onclick=()=>openScript(+b.dataset.script));
document.querySelector('#scriptFeature').onclick=()=>show('scripts');
function openScript(i){const s=serviceScripts[i];document.querySelectorAll('#scriptMenu button').forEach((b,n)=>b.classList.toggle('active',n===i));document.querySelector('#scriptViewer').innerHTML=`<small>SERVICE ${i+1} OF 9</small><h2>${s[0]} Sample Chat</h2><p class="scriptTip">Study how the agent follows the complete flow while adapting the wording to the service.</p><div class="scriptLines">${s[1].map((line,n)=>{const [stage,text]=line.split('|');return `<div class="scriptLine"><span>${stage}</span><p><b>Agent:</b> ${text}</p>${n===0?`<p class="customerLine"><b>Customer:</b> ${marketScenarios[i].opening}</p>`:''}</div>`}).join('')}</div><button class="practiceFromScript" onclick="startMarketPractice(${i})">Practice This Service with AI →</button>`}
openScript(0);
let activeScenario=marketScenarios[0],customerName=activeScenario.name;
window.startMarketPractice=i=>{activeScenario=marketScenarios[i];customerName=activeScenario.name;turn=1;answers=[];reply.disabled=false;sendBtn.disabled=false;document.querySelector('#practiceLabel').textContent=`${markets[i][0].toUpperCase()} • LIVE CHAT`;document.querySelector('#practiceTitle').textContent=activeScenario.title;document.querySelector('#practiceCustomer').innerHTML=`<b>Customer:</b> ${activeScenario.name}`;document.querySelector('#practiceSituation').innerHTML=`<b>Situation:</b> ${activeScenario.situation}`;chat.innerHTML=`<div class="customer"><b>${activeScenario.name}:</b> ${activeScenario.opening}</div>`;feedback.innerHTML=`<b>${markets[i][0]} scenario loaded.</b><p>Use the complete non-voice chat flow to handle this concern.</p>`;show('practice');scrollTo(0,0);reply.focus()};
const skills=[['Written Communication',88],['Empathy',92],['Problem Solving',81],['Product Knowledge',76],['Sales Skills',69]];
document.querySelector('#skills').innerHTML=skills.map(x=>`<div class="skillrow"><b>${x[0]}</b><span>${x[1]}%</span><div class="bar"><i style="width:${x[1]}%"></i></div></div>`).join('');
const reply=document.querySelector('#reply'),sendBtn=document.querySelector('#send'),chat=document.querySelector('#chat'),feedback=document.querySelector('#feedback');let turn=1,answers=[];reply.oninput=()=>document.querySelector('#count').textContent=`${reply.value.length} / 500 characters`;reply.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendBtn.click()}};
function addBubble(role,text){const d=document.createElement('div');d.className=role==='customer'?'customer':'student';d.style.cssText=role==='student'?'background:#1268d5;color:white;padding:14px;border-radius:12px 12px 2px 12px;max-width:75%;margin:12px 0 12px auto':'';d.innerHTML=`<b>${role==='customer'?customerName:'You'}:</b> ${text.replace(/</g,'&lt;')}`;chat.appendChild(d);d.scrollIntoView({behavior:'smooth'})}
function customerReply(t,n){return activeScenario.replies[Math.min(n-1,activeScenario.replies.length-1)]}
sendBtn.onclick=()=>{const t=reply.value.trim();if(t.length<8){feedback.innerHTML='<b>Please write a complete response.</b>';return}addBubble('student',t);answers.push(t);reply.value='';document.querySelector('#count').textContent='0 / 500 characters';sendBtn.disabled=true;feedback.textContent='Mia is typing…';setTimeout(()=>{addBubble('customer',customerReply(t,turn));turn++;sendBtn.disabled=false;feedback.textContent=`Conversation turn ${Math.min(turn,6)} of 6`;if(turn>6){reply.disabled=true;sendBtn.disabled=true;const a=answers.join(' '),checks=[/sorry|apolog|understand/i,/check|track|verify|investigate/i,/today|tomorrow|hour|minute|within/i,/refund|replacement|pickup|credit|option/i,/thank|anything else|assist|confirm/i];let score=35;checks.forEach((r,i)=>score+=r.test(a)?(i<4?15:5):0);feedback.innerHTML=`<div class="score">${score}/100</div><b>Conversation completed</b><p>Final score covers empathy, investigation, timeframe, solution, and professional closing.</p>`}else reply.focus()},650)};
