const titles={dashboard:'Skills Dashboard',learn:'Learning Modules',practice:'AI Practice Simulator',markets:'Industry Explorer',progress:'Progress & Mastery'};
function show(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));document.querySelector('#title').textContent=titles[id]}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>show(b.dataset.view));
const modules=[
['Introduction to Non-Voice Contact Center Services','Voice vs. non-voice; live chat, email, messaging, ticketing, social media support, back-office services, and common non-voice products and services.','Classify examples according to channel and service type.'],
['Written Communication Skills for Customer Service','Grammar, spelling, punctuation, sentence construction, clarity, conciseness, professional vocabulary, and avoiding inappropriate slang or text language.','Edit poorly written customer-service messages.'],
['Professional Tone, Netiquette, and Customer Empathy','Professional online behavior, positive language, courtesy, empathy, cultural sensitivity, and adapting written tone for different customers.','Rewrite negative messages using professional and empathetic language.'],
['Understanding Customer Concerns and Non-Voice Probing','Reading comprehension, identifying customer intent, analyzing the concern, open- and closed-ended questions, clarification, verification, and probing techniques.','Analyze customer messages and prepare appropriate probing questions.'],
['The Non-Voice Chat Flow and Actual Script Analysis','Opening → Verification → Acknowledgment → Probing → Resolution → Confirmation → Additional Assistance → Closing.','Label every part of the sample script.',`Agent: Good morning! Thank you for contacting ABC Online Support. My name is Ana. How may I assist you today?\nCustomer: My order has not arrived.\nAgent: I’m sorry about the delay. I understand how important it is to receive your order on time. May I have your order number for verification?\nCustomer: It is 48291.\nAgent: Thank you. When did the tracking status last change?\nCustomer: Three days ago.\nAgent: I checked the order and it is at the local delivery hub. I will contact the courier and update you within two hours. Would that be acceptable?\nCustomer: Yes, thank you.\nAgent: You’re welcome. Is there anything else I can assist you with today?\nCustomer: None.\nAgent: Thank you for contacting ABC Online Support. Have a great day!`],
['Chat and Email Response Writing','Professional chat responses and emails; greetings, acknowledgment, empathy, hold statements, resolutions, email structure, and professional closings.','Answer one chat concern and compose one support email.'],
['Handling Difficult Customers and Common Scenarios','Angry, impatient, confused, and dissatisfied customers; complaints, billing, refunds, orders, accounts, and basic technical concerns.','Respond to three difficult-customer scenarios.'],
['Problem Solving, Knowledge Base, Escalation, and Documentation','Knowledge base and FAQ searches, solutions, policies, escalation, transfers, ticket creation, disposition, and case notes.','Resolve a case and prepare its ticket notes.'],
['Non-Voice Quality Standards and Guided Practice','Accuracy, grammar, tone, empathy, response time, completeness, data privacy, documentation, QA scoring, and guided scenario practice.','Score and improve a sample conversation.'],
['Mock and Final Non-Voice Simulation','Students independently perform realistic chat and email transactions using the complete process; the teacher evaluates performance using a rubric.','Complete the timed mock, review feedback, and take the final simulation.']
];
document.querySelector('#modules').innerHTML=modules.map((m,i)=>`<article class="lessoncard" data-lesson="${i}"><label>LESSON ${i+1}</label><h3>${m[0]}</h3><p>${m[1]}</p><button>View Lesson →</button></article>`).join('');
document.querySelectorAll('.lessoncard').forEach(c=>c.onclick=()=>openLesson(+c.dataset.lesson));
function openLesson(i){const m=modules[i];document.querySelectorAll('.lessoncard').forEach((c,n)=>c.classList.toggle('selected',n===i));document.querySelector('#lessonDetail').innerHTML=`<small>LESSON ${i+1} OF 10</small><h2>${m[0]}</h2><p>${m[1]}</p>${i===4?`<h3>Complete Chat Flow</h3><div class="flow">Opening → Verification → Acknowledgment → Probing → Resolution → Confirmation → Additional Assistance → Closing</div>`:''}${m[3]?`<h3>Sample Customer-Service Script</h3><div class="sample">${m[3]}</div>`:''}<h3>Student Activity</h3><div class="activity">${m[2]}</div>`;document.querySelector('#lessonDetail').scrollIntoView({behavior:'smooth',block:'start'})}
const markets=[['E-commerce & Retail','Order support, returns, refunds, product inquiries'],['Banking & Finance','Account support, verification, fraud reporting'],['Telecommunications','Billing, plan changes, connectivity support'],['Healthcare','Appointment, benefits, and patient-service support'],['Travel & Hospitality','Reservations, rebooking, guest assistance'],['Technology & SaaS','Help desk, onboarding, subscription support'],['Logistics','Tracking, delivery coordination, claims'],['Insurance','Policy inquiries, claims intake, documentation'],['Education & Government','Enrollment, public information, service requests']];
document.querySelector('#marketgrid').innerHTML=markets.map(x=>`<article><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('');
const skills=[['Written Communication',88],['Empathy',92],['Problem Solving',81],['Product Knowledge',76],['Sales Skills',69]];
document.querySelector('#skills').innerHTML=skills.map(x=>`<div class="skillrow"><b>${x[0]}</b><span>${x[1]}%</span><div class="bar"><i style="width:${x[1]}%"></i></div></div>`).join('');
const reply=document.querySelector('#reply'),sendBtn=document.querySelector('#send'),chat=document.querySelector('#chat'),feedback=document.querySelector('#feedback');let turn=1,answers=[];reply.oninput=()=>document.querySelector('#count').textContent=`${reply.value.length} / 500 characters`;reply.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendBtn.click()}};
function addBubble(role,text){const d=document.createElement('div');d.className=role==='customer'?'customer':'student';d.style.cssText=role==='student'?'background:#1268d5;color:white;padding:14px;border-radius:12px 12px 2px 12px;max-width:75%;margin:12px 0 12px auto':'';d.innerHTML=`<b>${role==='customer'?'Mia':'You'}:</b> ${text.replace(/</g,'&lt;')}`;chat.appendChild(d);d.scrollIntoView({behavior:'smooth'})}
function customerReply(t,n){if(n===1)return /sorry|apolog|understand/i.test(t)?'Thank you for understanding. Can you check it? My order number is BNHS-48291.':'Can you check it? My order number is BNHS-48291.';if(n===2)return /check|track|verify|investigate/i.test(t)?'Tracking says “in transit.” Can it arrive before tomorrow afternoon?':'Will you check the tracking for me?';if(n===3)return /today|tomorrow|hour|minute|within/i.test(t)?'If it cannot arrive, what other option can you offer?':'When exactly will you update me?';if(n===4)return /refund|replacement|pickup|credit|option/i.test(t)?'A pickup replacement would help. Is there an extra charge?':'Can I get a replacement or refund?';if(n===5)return 'That works. Please arrange it. Is there anything else you need?';return 'Thank you for helping me. I appreciate the clear update.'}
sendBtn.onclick=()=>{const t=reply.value.trim();if(t.length<8){feedback.innerHTML='<b>Please write a complete response.</b>';return}addBubble('student',t);answers.push(t);reply.value='';document.querySelector('#count').textContent='0 / 500 characters';sendBtn.disabled=true;feedback.textContent='Mia is typing…';setTimeout(()=>{addBubble('customer',customerReply(t,turn));turn++;sendBtn.disabled=false;feedback.textContent=`Conversation turn ${Math.min(turn,6)} of 6`;if(turn>6){reply.disabled=true;sendBtn.disabled=true;const a=answers.join(' '),checks=[/sorry|apolog|understand/i,/check|track|verify|investigate/i,/today|tomorrow|hour|minute|within/i,/refund|replacement|pickup|credit|option/i,/thank|anything else|assist|confirm/i];let score=35;checks.forEach((r,i)=>score+=r.test(a)?(i<4?15:5):0);feedback.innerHTML=`<div class="score">${score}/100</div><b>Conversation completed</b><p>Final score covers empathy, investigation, timeframe, solution, and professional closing.</p>`}else reply.focus()},650)};
