const titles={dashboard:'Skills Dashboard',learn:'Learning Modules',practice:'AI Practice Simulator',markets:'Industry Explorer',progress:'Progress & Mastery'};
function show(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));document.querySelector('#title').textContent=titles[id]}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>show(b.dataset.view));
const modules=[
['Introduction to Non-Voice Contact Center Services','Voice vs. non-voice; live chat, email, messaging, ticketing, social media support, back-office services, and common non-voice products and services.','Classify examples according to channel and service type.'],
['Written Communication Skills for Customer Service','Grammar, spelling, punctuation, sentence construction, clarity, conciseness, professional vocabulary, and avoiding inappropriate slang or text language.','Edit poorly written customer-service messages.'],
['Professional Tone, Netiquette, and Customer Empathy','Professional online behavior, positive language, courtesy, empathy, cultural sensitivity, and adapting written tone for different customers.','Rewrite negative messages using professional and empathetic language.'],
['Understanding Customer Concerns and Non-Voice Probing','Reading comprehension, identifying customer intent, analyzing the concern, open- and closed-ended questions, clarification, verification, and probing techniques.','Analyze customer messages and prepare appropriate probing questions.'],
['The Non-Voice Chat Flow and Actual Script Analysis','Opening → Verification → Acknowledgment → Probing → Resolution → Confirmation → Additional Assistance → Closing.','Label every part of the sample script.',`Agent: Good morning! Thank you for contacting ABC Online Support. My name is Ana. How may I assist you today?\nCustomer: My order has not arrived.\nAgent: I’m sorry about the delay. I understand how important it is to receive your order on time. May I have your order number for verification?\nCustomer: It is 48291.\nAgent: Thank you. When did the tracking status last change?\nCustomer: Three days ago.\nAgent: I checked the order and it is at the local delivery hub. I will contact the courier and update you within two hours. Would that be acceptable?\nCustomer: Yes, thank you.\nAgent: You’re welcome. Is there anything else I can assist you with today?\nCustomer: None.\nAgent: Thank you for contacting ABC Online Support. Have a great day!`],
['Chat and Email Response Writing','Professional chat responses and emails; greetings, acknowledgment, empathy, hold statements, resolutions, email structure, and professional closings.','Answer one chat concern and compose one support email.'],
['Handling Difficult Customers and Common Scenarios','Angry, impatient, confused, and dissatisfied customers; complaints, billing, refunds, orders, accounts, and basic technical concerns.','Respond to three difficult-customer scenarios.'],
['Problem Solving, Knowledge Base, Escalation, and Documentation','Knowledge base and FAQ searches, solutions, policies, escalation, transfers, ticket creation, disposition, and case notes.','Resolve a case and prepare its ticket notes.'],
['Non-Voice Quality Standards and Guided Practice','Accuracy, grammar, tone, empathy, response time, completeness, data privacy, documentation, QA scoring, and guided scenario practice.','Score and improve a sample conversation.'],
['Mock and Final Non-Voice Simulation','Students independently perform realistic chat and email transactions using the complete process; the teacher evaluates performance using a rubric.','Complete the timed mock, review feedback, and take the final simulation.']
];
document.querySelector('#modules').innerHTML=modules.map((m,i)=>`<article class="lessoncard" data-lesson="${i}"><label>LESSON ${i+1}</label><h3>${m[0]}</h3><p>${m[1]}</p><button>Open Lesson in New Tab ↗</button></article>`).join('');
document.querySelectorAll('.lessoncard').forEach(c=>c.onclick=()=>window.open(`index.html?lesson=${c.dataset.lesson}`,'_blank'));
const lessonBodies=[
 {objectives:['Define non-voice contact center services','Differentiate voice and non-voice transactions','Identify products, services, and employment markets'],sections:[['What is non-voice support?','Non-voice support assists customers through written digital channels. Agents must understand the concern, find accurate information, and provide a clear written resolution without relying on spoken explanations.'],['Major channels','Live chat provides real-time written assistance. Email handles detailed or non-urgent concerns. Messaging and social media support customers on mobile platforms. Ticketing records and tracks cases. Back-office work includes data entry, verification, order processing, and content review.'],['Potential markets','E-commerce, banking, telecommunications, healthcare, travel, technology, logistics, insurance, education, and government all use non-voice services.']],example:'A customer asking where an online order is should be handled through live chat or messaging. A request requiring documents and a detailed explanation is often better handled through email or ticketing.',check:['What makes a transaction non-voice?','Name four non-voice channels.','Give two industries that hire non-voice agents.']},
 {objectives:['Apply correct grammar and punctuation','Write concise customer-friendly sentences','Use professional vocabulary'],sections:[['Accuracy matters','Incorrect grammar or spelling can change meaning and reduce customer confidence. Agents must proofread names, dates, amounts, instructions, and policy information.'],['Clarity and conciseness','Use short complete sentences, one idea at a time, and familiar words. Remove repetition, unnecessary fillers, excessive capitalization, and multiple punctuation marks.'],['Professional language','Avoid shortcuts such as “u,” “pls,” “ASAP!!!,” and informal slang. Use “you,” “please,” “I will check this for you,” and other complete expressions.']],example:'Weak: “pls wait im checking ur acc.”\nImproved: “Please allow me a moment while I review your account.”',check:['Correct this: “your order have been ship.”','Why should agents avoid text-message shortcuts?','What information must always be proofread?']},
 {objectives:['Use appropriate netiquette','Demonstrate empathy in writing','Adapt tone to customer emotions and culture'],sections:[['Professional netiquette','Greet the customer, respond respectfully, avoid typing in all caps, do not argue, and never make jokes that may be misunderstood. Maintain privacy and stay focused on the concern.'],['Empathy and acknowledgment','Acknowledgment shows that the concern was understood. Empathy recognizes its effect on the customer. Use genuine statements connected to the specific situation.'],['Positive language','Focus on what can be done. Replace “That is impossible” with “Here are the available options.” Avoid blaming the customer, another department, or the company.']],example:'“I understand how frustrating it is to be charged twice. I’ll review both transactions and help you resolve this.”',check:['What is the difference between acknowledgment and empathy?','Rewrite: “You entered the wrong information.”','Why can humor be risky in live chat?']},
 {objectives:['Identify the customer’s main intent','Distinguish open and closed questions','Use clarification, verification, and probing'],sections:[['Read before responding','Review the whole message and separate the main concern from supporting details. Do not ask for information the customer already provided.'],['Types of questions','Open questions gather explanations: “What happened before the error appeared?” Closed questions confirm facts: “Did you receive a confirmation email?” Clarifying questions remove ambiguity, while verification confirms identity or transaction details.'],['Effective probing','Ask one relevant question at a time. Explain why sensitive information is needed, follow data-privacy rules, and summarize the facts before giving a solution.']],example:'Customer: “It does not work.”\nUseful probes: “Which feature are you trying to use?” “What message appears on the screen?” “When did the problem begin?”',check:['What is the customer’s intent? “I paid yesterday but my balance is unchanged.”','Write one open and one closed question.','Why should agents avoid repeated questions?']},
 {objectives:['Follow the eight-stage chat flow','Analyze an actual chat script','Use transitions naturally'],sections:[['Opening and verification','Welcome the customer, introduce yourself, offer assistance, and verify only the information required by policy.'],['Acknowledgment, probing, and resolution','Recognize the concern and its impact, ask focused questions, consult the correct resource, then give an accurate resolution and timeframe.'],['Confirmation and closing','Confirm that the solution is understood, offer additional assistance, thank the customer, and close professionally.']],example:'Use the sample script below. Notice how the agent does not give a solution before verification and probing.',check:['Which stage comes after acknowledgment?','Why must the agent confirm the resolution?','Identify the closing statement in the sample script.']},
 {objectives:['Construct professional chat messages','Write a properly structured support email','Use hold and closing statements'],sections:[['Chat response structure','A strong response usually contains acknowledgment, empathy when appropriate, action, and expectation. Keep messages readable and send updates during long checks.'],['Hold procedure','Ask permission before a hold, give a reasonable duration, return within the promised time, thank the customer for waiting, and provide an update.'],['Email structure','Use a clear subject, greeting, acknowledgment, organized explanation, action or next step, additional-assistance line, and professional signature.']],example:'Subject: Update on Order 48291\nDear Ms. Santos,\nI’m sorry for the delivery delay. I contacted the courier and requested priority delivery. You will receive another update within two hours.\nSincerely,\nAna | Customer Support',check:['What four parts should a strong chat response contain?','Write a proper hold statement.','What makes an email subject effective?']},
 {objectives:['De-escalate difficult conversations','Respond to common support scenarios','Offer realistic policy-compliant options'],sections:[['Control the interaction','Stay calm, acknowledge the concern, avoid defensive language, and focus on facts and solutions. Never tell a customer to “calm down.”'],['Common difficult behaviors','An angry customer needs acknowledgment and action. An impatient customer needs a clear timeframe. A confused customer needs simple steps. A dissatisfied customer needs confirmation that the proposed option addresses the concern.'],['Boundaries and promises','Do not invent policies, guarantee outcomes outside your control, or provide unauthorized refunds. Explain available options and escalate when necessary.']],example:'Instead of “That is not our fault,” write: “I understand why this is concerning. Let me review the transaction and identify the available solution.”',check:['Why should an agent avoid telling a customer to calm down?','How do you respond to an impatient customer?','When should a complaint be escalated?']},
 {objectives:['Use a knowledge base effectively','Apply escalation rules','Create complete case documentation'],sections:[['Knowledge-base search','Use specific keywords, confirm that the article matches the product and current policy, follow the steps in order, and translate technical instructions into customer-friendly language.'],['Escalation','Escalate when access or authority is insufficient, a policy exception is requested, a security or safety issue exists, or troubleshooting has failed. Explain the transfer and pass complete context.'],['Documentation','Record the customer’s concern, verified information, troubleshooting performed, solution offered, commitments, follow-up time, and disposition. Use objective language.']],example:'Case note: “Customer reported duplicate charge of ₱850 dated 1 September. Verified both transaction IDs. Explained pending-charge policy and escalated to Billing Review. Advised update within 24 hours.”',check:['What should be checked before using a knowledge article?','List two reasons for escalation.','What information belongs in a case note?']},
 {objectives:['Apply non-voice QA standards','Protect customer data','Evaluate and improve a transcript'],sections:[['Core QA standards','Quality reviews measure accuracy, grammar, tone, empathy, completeness, process compliance, response time, resolution, and documentation. Critical errors may outweigh other good performance.'],['Data privacy','Collect only necessary information, use approved verification, never request passwords or one-time PINs, avoid copying personal data into unauthorized tools, and follow retention rules.'],['Guided practice','Review the scenario, draft a response, compare it with the rubric, revise weak areas, and repeat until the required score is reached.']],example:'A grammatically perfect response still fails QA if it gives the wrong refund policy or exposes personal information.',check:['Name five non-voice QA criteria.','What information must an agent never request?','Why is accuracy more important than speed?']},
 {objectives:['Complete an end-to-end chat or email case','Work independently within time limits','Meet the teacher’s performance rubric'],sections:[['Mock simulation','The mock reproduces the assessment conditions. Students receive a customer scenario, use the full chat flow, document the case, and review detailed teacher feedback.'],['Final simulation','Students independently handle one chat and one email concern. The teacher evaluates written communication, empathy, probing, resolution, process compliance, documentation, and efficiency.'],['Suggested scoring','Written communication 20%; tone and empathy 15%; probing and verification 15%; accurate resolution 20%; chat flow 15%; documentation and privacy 10%; efficiency 5%.']],example:'Passing recommendation: at least 75% overall with no critical error involving privacy, verification, misinformation, or unprofessional conduct.',check:['What are the two required final transactions?','Which performance area has the highest suggested weight?','What is considered a critical error?']}
];
const knowledgeAnswers=[
 ['It uses written digital channels instead of a phone conversation.','Live chat, email, messaging, ticketing, social media, and back-office processing are examples.','Examples include e-commerce, banking, telecommunications, healthcare, travel, and technology.'],
 ['Correct: “Your order has been shipped.”','Shortcuts can appear careless, confuse customers, and damage professional credibility.','Names, dates, amounts, order numbers, instructions, and policy details must be proofread.'],
 ['Acknowledgment confirms the concern; empathy recognizes how the situation affects the customer.','Improved: “Let me help you correct the information so we can continue.”','Written humor can be misunderstood because tone and facial expressions are absent.'],
 ['The customer wants confirmation that yesterday’s payment will be posted to the account.','Open: “What happened after you submitted the payment?” Closed: “Did you receive a receipt?”','Repeated questions frustrate customers and show that the agent did not read carefully.'],
 ['Probing comes after acknowledgment.','Confirmation ensures the customer understands and accepts the proposed resolution.','The final thank-you and well-wish form the closing statement.'],
 ['Acknowledgment, empathy, action, and expectation.','“May I place the chat on hold for two minutes while I review your account?”','A useful subject states the purpose clearly, such as “Update on Order 48291.”'],
 ['It sounds dismissive and can make the customer more upset.','Acknowledge the urgency and give an honest, specific timeframe.','Escalate when authority is insufficient, a policy exception is needed, or risk/security is involved.'],
 ['Confirm that it matches the correct product, issue, customer type, and current policy.','Examples: insufficient authority, failed troubleshooting, security risk, or requested policy exception.','Concern, verification, steps taken, resolution, commitments, follow-up time, and disposition.'],
 ['Accuracy, grammar, tone, empathy, completeness, response time, privacy, resolution, and documentation.','Never request a password or one-time PIN.','A fast but incorrect answer can harm the customer and create a critical quality failure.'],
 ['One live-chat transaction and one email transaction.','Written communication and accurate resolution receive the highest suggested weights at 20% each.','Examples include privacy violations, failed verification, misinformation, and unprofessional conduct.']
];
function openLesson(i){const m=modules[i],b=lessonBodies[i],done=localStorage.getItem(`bnhs-lesson-${i}`)==='done';document.querySelectorAll('.lessoncard').forEach((c,n)=>c.classList.toggle('selected',n===i));document.querySelector('#lessonDetail').innerHTML=`<div class="lessonTop"><div><small>INTERACTIVE LESSON ${i+1} OF 10</small><h1>${m[0]}</h1></div><span class="status ${done?'complete':''}" id="lessonStatus">${done?'✓ Completed':'In progress'}</span></div><div class="lessonProgress"><i style="width:${(i+1)*10}%"></i></div><section class="lessonBlock"><h2>Why This Lesson Matters</h2><p>${m[1]}</p><p>As a non-voice agent, you must apply this knowledge while reading, thinking, and responding under time pressure. Study the explanations and connect each idea to the examples before attempting the activity.</p></section><section class="lessonBlock"><h2>Learning Objectives</h2><ul>${b.objectives.map(x=>`<li>${x}</li>`).join('')}</ul></section>${b.sections.map((x,n)=>`<details class="topic" ${n===0?'open':''}><summary>${n+1}. ${x[0]}</summary><div><p>${x[1]}</p><p><b>Think about it:</b> How would this concept affect the customer’s experience if an agent ignored it?</p></div></details>`).join('')}${i===4?`<section class="lessonBlock"><h2>Complete Chat Flow</h2><div class="flow">Opening → Verification → Acknowledgment → Probing → Resolution → Confirmation → Additional Assistance → Closing</div><p>Each stage has a purpose. Skipping verification can create a privacy risk, while skipping confirmation may leave the customer unsure whether the concern was resolved.</p></section>`:''}<section class="lessonBlock"><h2>Worked Example</h2><div class="sample">${b.example}</div></section>${m[3]?`<section class="lessonBlock"><h2>Actual Sample Script</h2><div class="sample">${m[3]}</div></section>`:''}<section class="lessonBlock"><h2>Try It Yourself</h2><div class="activity">${m[2]}</div><textarea class="studentWork" id="studentWork" placeholder="Write your answer, analysis, or draft response here..."></textarea><button class="saveWork" onclick="saveWork(${i})">Save My Work</button><span id="saveNote"></span></section><section class="lessonBlock"><h2>Interactive Knowledge Check</h2><p>Answer each question first, then reveal the suggested answer.</p>${b.check.map((x,q)=>`<div class="question"><b>${q+1}. ${x}</b><textarea placeholder="Type your answer..."></textarea><button onclick="revealAnswer(${i},${q},this)">Show Suggested Answer</button><div class="answer"></div></div>`).join('')}</section><div class="lessonNav"><button ${i===0?'disabled':''} onclick="goLesson(${i-1})">← Previous Lesson</button><button class="completeBtn" onclick="completeLesson(${i})">✓ Mark Lesson Complete</button><button ${i===9?'disabled':''} onclick="goLesson(${i+1})">Next Lesson →</button></div>`;document.querySelector('#studentWork').value=localStorage.getItem(`bnhs-work-${i}`)||'';document.querySelector('#lessonDetail').scrollIntoView({block:'start'})}
window.revealAnswer=(i,q,btn)=>{const box=btn.nextElementSibling;box.textContent=knowledgeAnswers[i][q];box.classList.toggle('show');btn.textContent=box.classList.contains('show')?'Hide Suggested Answer':'Show Suggested Answer'};
window.saveWork=i=>{localStorage.setItem(`bnhs-work-${i}`,document.querySelector('#studentWork').value);document.querySelector('#saveNote').textContent=' ✓ Saved on this device'};
window.completeLesson=i=>{localStorage.setItem(`bnhs-lesson-${i}`,'done');document.querySelector('#lessonStatus').className='status complete';document.querySelector('#lessonStatus').textContent='✓ Completed'};
window.goLesson=i=>{location.href=`index.html?lesson=${i}`};
const selectedLesson=new URLSearchParams(location.search).get('lesson');if(selectedLesson!==null&&!Number.isNaN(+selectedLesson)&&+selectedLesson>=0&&+selectedLesson<10){show('learn');document.body.classList.add('lessonMode');document.querySelector('#modules').style.display='none';openLesson(+selectedLesson)}
const markets=[['E-commerce & Retail','Order support, returns, refunds, product inquiries'],['Banking & Finance','Account support, verification, fraud reporting'],['Telecommunications','Billing, plan changes, connectivity support'],['Healthcare','Appointment, benefits, and patient-service support'],['Travel & Hospitality','Reservations, rebooking, guest assistance'],['Technology & SaaS','Help desk, onboarding, subscription support'],['Logistics','Tracking, delivery coordination, claims'],['Insurance','Policy inquiries, claims intake, documentation'],['Education & Government','Enrollment, public information, service requests']];
document.querySelector('#marketgrid').innerHTML=markets.map(x=>`<article><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('');
const skills=[['Written Communication',88],['Empathy',92],['Problem Solving',81],['Product Knowledge',76],['Sales Skills',69]];
document.querySelector('#skills').innerHTML=skills.map(x=>`<div class="skillrow"><b>${x[0]}</b><span>${x[1]}%</span><div class="bar"><i style="width:${x[1]}%"></i></div></div>`).join('');
const reply=document.querySelector('#reply'),sendBtn=document.querySelector('#send'),chat=document.querySelector('#chat'),feedback=document.querySelector('#feedback');let turn=1,answers=[];reply.oninput=()=>document.querySelector('#count').textContent=`${reply.value.length} / 500 characters`;reply.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendBtn.click()}};
function addBubble(role,text){const d=document.createElement('div');d.className=role==='customer'?'customer':'student';d.style.cssText=role==='student'?'background:#1268d5;color:white;padding:14px;border-radius:12px 12px 2px 12px;max-width:75%;margin:12px 0 12px auto':'';d.innerHTML=`<b>${role==='customer'?'Mia':'You'}:</b> ${text.replace(/</g,'&lt;')}`;chat.appendChild(d);d.scrollIntoView({behavior:'smooth'})}
function customerReply(t,n){if(n===1)return /sorry|apolog|understand/i.test(t)?'Thank you for understanding. Can you check it? My order number is BNHS-48291.':'Can you check it? My order number is BNHS-48291.';if(n===2)return /check|track|verify|investigate/i.test(t)?'Tracking says “in transit.” Can it arrive before tomorrow afternoon?':'Will you check the tracking for me?';if(n===3)return /today|tomorrow|hour|minute|within/i.test(t)?'If it cannot arrive, what other option can you offer?':'When exactly will you update me?';if(n===4)return /refund|replacement|pickup|credit|option/i.test(t)?'A pickup replacement would help. Is there an extra charge?':'Can I get a replacement or refund?';if(n===5)return 'That works. Please arrange it. Is there anything else you need?';return 'Thank you for helping me. I appreciate the clear update.'}
sendBtn.onclick=()=>{const t=reply.value.trim();if(t.length<8){feedback.innerHTML='<b>Please write a complete response.</b>';return}addBubble('student',t);answers.push(t);reply.value='';document.querySelector('#count').textContent='0 / 500 characters';sendBtn.disabled=true;feedback.textContent='Mia is typing…';setTimeout(()=>{addBubble('customer',customerReply(t,turn));turn++;sendBtn.disabled=false;feedback.textContent=`Conversation turn ${Math.min(turn,6)} of 6`;if(turn>6){reply.disabled=true;sendBtn.disabled=true;const a=answers.join(' '),checks=[/sorry|apolog|understand/i,/check|track|verify|investigate/i,/today|tomorrow|hour|minute|within/i,/refund|replacement|pickup|credit|option/i,/thank|anything else|assist|confirm/i];let score=35;checks.forEach((r,i)=>score+=r.test(a)?(i<4?15:5):0);feedback.innerHTML=`<div class="score">${score}/100</div><b>Conversation completed</b><p>Final score covers empathy, investigation, timeframe, solution, and professional closing.</p>`}else reply.focus()},650)};
